export enum QUERY_KEY {
  ANIME_HOME_PAGE = "ANIME_HOME_PAGE",
  ANIME_EPISODES_BY_ID = "ANIME_EPISODES_BY_ID",
  ANIME_EPISODE_SERVERS = "ANIME_EPISODE_SERVERS",
  WATCH_ANIME_BY_EPISODE_ID = "WATCH_ANIME_BY_EPISODE_ID",
  ANIME_INFO = "ANIME_INFO",

  LATEST_ANIME_EPISODES = "latest_anime_episodes",
  UPCOMING_SCHEDULE = "uncoming_schedule",
  SEARCHED_ANIMES = "searched_animes",
}
